// Verification data models — pure types, no runtime dependencies.
// These are the canonical shapes shared across all verification infrastructure.

// ─── Contact channel ─────────────────────────────────────────────────────────
// A discriminated union representing the channel through which a verification
// message will be sent. The 'type' discriminant aligns with the contact_type
// enum defined in the TRK constitutional schema.
export type ContactChannel =
  | { readonly type: 'phone'; readonly value: string }
  | { readonly type: 'email'; readonly value: string };

// ─── Verification message ─────────────────────────────────────────────────────
// The payload delivered to a contact channel.
// Subject is required so the routing layer never invents policy.
// For SMS, the provider implementation may ignore it.
// Composition of body and subject is the responsibility of the verification
// workflow (future sprint) — not of the transport routing layer.
export interface VerificationMessage {
  readonly subject: string;
  readonly body: string;
}

// ─── Verification status ─────────────────────────────────────────────────────
// Describes the lifecycle position of a single verification record in the cache.
// Transitions are unidirectional: pending → delivered → consumed | expired.
// The cache does not enforce transitions — that is the responsibility of the
// verification workflow implemented in a future sprint.
export type VerificationStatus =
  | 'pending'    // Created; send to provider has not yet been confirmed.
  | 'delivered'  // Provider confirmed the message was accepted for delivery.
  | 'consumed'   // The verification was successfully used and is now exhausted.
  | 'expired';   // The record's expiresAt has passed; no further use is valid.

// ─── Verification record ─────────────────────────────────────────────────────
// The unit of state stored in the VerificationCache.
// Records are ephemeral — they exist only in the cache, never in the database.
// Each record is keyed by a unique 'id' generated by the caller.
export interface VerificationRecord {
  readonly id: string;
  readonly channel: ContactChannel;
  readonly status: VerificationStatus;
  readonly createdAt: Date;
  readonly expiresAt: Date;
}
